import sqlite3
conn = sqlite3.connect('db.sqlite3')
cur = conn.cursor()
title = input('title? ')
body = input('body? ')
cur.execute('INSERT INTO topics (title, body) VALUES(?, ?)', (title, body))
conn.commit()
cur.execute('SELECT * FROM topics WHERE id = ?', (cur.lastrowid,))
topics = cur.fetchall()
conn.close()
print(topics)